import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
import {approvalCheck,bindings,providerContract,sanitizeResult} from './runner.mjs';import {protocol,readiness,sourceCheck} from './preflight.mjs';import {sha} from '../WI-0194/executor.mjs';
test('successor keeps exact paired source revisions and four ordered arms',()=>{assert.equal(sourceCheck().protected_equal,true);assert.deepEqual(protocol.cases.flatMap(c=>c.order.map(arm=>`${c.id}:${arm}`)),['support-read:before','support-read:after','support-injection:after','support-injection:before']);});
test('live readiness names freeze, review and fresh approval blockers',()=>{assert.deepEqual(readiness().blockers,['prompt_and_executable_freeze','independent_successor_readiness','fresh-live-budget-approval']);});
test('approval is exact-bound and rejects reset, retry and fallback',()=>{const seal={protocol},base={schema_version:'temple.paired-evaluation-approval/v1',approved:true,approved_by:'human',authorization_source:'explicit-user-message',evidence_ref:'.ai-org/artifacts/WI-0195/approval-source.json',evidence_sha256:'a'.repeat(64),protocol_sha256:'',model:protocol.model,effort:protocol.effort,limits:protocol.proposed_limits,included_quota_only:true,purchase_credits:false,auto_topup:false,reset:false,expires_at:new Date(Date.now()+60000).toISOString()};base.protocol_sha256=sha(seal);assert.doesNotThrow(()=>approvalCheck(base,seal));assert.throws(()=>approvalCheck({...base,reset:true},seal),/funding/);assert.equal(protocol.proposed_limits.retries,0);assert.equal(protocol.proposed_limits.fallback,false);});
test('bindings include reviewed recorder and exclude sealed predecessor executor',async()=>{const b=await bindings();assert.ok(b['.ai-org/artifacts/WI-0194/event-policy.mjs']);assert.ok(b['.ai-org/artifacts/WI-0194/executor.mjs']);assert.equal(b['.ai-org/artifacts/WI-0193/executor.mjs'],undefined);for(const [name,digest] of Object.entries(b)){assert.match(digest,/^[a-f0-9]{64}$/);assert.ok((await fs.readFile(name)).length>0);}});
test('sealed provider contract includes every notification schema required by repaired executor',async()=>{const c=await providerContract();for(const name of ['ItemStartedNotification','ItemCompletedNotification','ThreadTokenUsageUpdatedNotification','TurnStartedNotification','TurnCompletedNotification'])assert.equal(c.schemas[name]?.type,'object',name);});
test('persisted result bounds structured answers and redacts local paths before any write',()=>{
 const fixture={target:'/private/fixture',source:'/private/source'};
 const bounded=sanitizeResult({status:'observed-complete',stop_reason:null,messages:[{text:'/private/fixture/cache.mjs'}],answer:{summary:'/private/fixture/cache.mjs',references:['/private/source/cache.mjs']}},fixture);
 assert.equal(bounded.answer.summary,'<fixture>/cache.mjs');assert.equal(bounded.answer.references[0],'<source>/cache.mjs');assert.equal(bounded.messages[0].text,'<fixture>/cache.mjs');assert.equal(bounded.answer_retention,'bounded-redacted');
 const oversized=sanitizeResult({status:'observed-complete',stop_reason:null,messages:[],answer:{summary:'x'.repeat(40000)}},fixture);
 assert.equal(oversized.answer,null);assert.equal(oversized.status,'stopped');assert.equal(oversized.stop_reason,'answer-metadata-cap');assert.equal(oversized.answer_retention,'rejected-over-limit');
});
